export const POST_CASE_REQUEST="POST_CASE_REQUEST";
export const POST_CASE_SUCCESS="POST_CASE_SUCCESS";
export const POST_CASE_FAIL="POST_CASE_FAIL";
export const POST_CASE_RESET="POST_CASE_RESET";


export const PUT_CASE_REQUEST="PUT_CASE_REQUEST";
export const PUT_CASE_SUCCESS="PUT_CASE_SUCCESS";
export const PUT_CASE_FAIL="PUT_CASE_FAIL";
export const PUT_CASE_RESET="PUT_CASE_RESET";

export const DELETE_CASE_REQUEST="DELETE_CASE_REQUEST";
export const DELETE_CASE_SUCCESS="DELETE_CASE_SUCCESS";
export const DELETE_CASE_FAIL="DELETE_CASE_FAIL";
export const DELETE_CASE_RESET="DELETE_CASE_RESET";

export const GET_CASES_REQUEST="GET_CASES_REQUEST";
export const GET_CASES_SUCCESS="GET_CASES_SUCCESS";
export const GET_CASES_FAIL="GET_CASES_FAIL";
export const GET_CASES_RESET="GET_CASES_RESET";


export const CASE_DETAIL_REQUEST="CASE_DETAIL_REQUEST";
export const CASE_DETAIL_SUCCESS="CASE_DETAIL_SUCCESS";
export const CASE_DETAIL_FAIL="CASE_DETAIL_FAIL";
export const CASE_DETAIL_RESET_REQUEST="CASE_DETAIL_RESET";