export const GET_CLIENTS_REQUEST="GET_CLIENTS_REQUEST";
export const GET_CLIENTS_SUCCESS="GET_CLIENTS_SUCCESS";
export const GET_CLIENTS_FAIL="GET_CLIENTS_FAIL";
export const GET_CLIENTS_RESET="GET_CLIENTS_RESET";



export const POST_CLIENT_REQUEST="POST_CLIENT_REQUEST";
export const POST_CLIENT_SUCCESS="POST_CLIENT_SUCCESS";
export const POST_CLIENT_FAIL="POST_CLIENT_FAIL";
export const POST_CLIENT_RESET="POST_CLIENT_RESET";


export const DELETE_CLIENT_REQUEST="DELETE_CLIENT_REQUEST";
export const DELETE_CLIENT_SUCCESS="DELETE_CLIENT_SUCCESS";
export const DELETE_CLIENT_FAIL="DELETE_CLIENT_FAIL";
export const DELETE_CLIENT_RESET="DELETE_CLIENT_RESET";



export const PUT_CLIENT_REQUEST="PUT_CLIENT_REQUEST";
export const PUT_CLIENT_SUCCESS="PUT_CLIENT_SUCCESS";
export const PUT_CLIENT_FAIL="PUT_CLIENT_FAIL";
export const PUT_CLIENT_RESET="PUT_CLIENT_RESET";


export const CLIENT_DETAIL_REQUEST="CLIENT_DETAIL_REQUEST";
export const CLIENT_DETAIL_SUCCESS="CLIENT_DETAIL_SUCCESS";
export const CLIENT_DETAIL_FAIL="CLIENT_DETAIL_FAIL";
export const CLIENT_DETAIL_RESET="CLIENT_DETAIL_RESET";